"""doctring"""
# Generated by Django 3.2.9 on 2021-12-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('doc_id', models.IntegerField(verbose_name='doc_id')),
                ('query', models.CharField(max_length=64, verbose_name='query')),
                ('answer', models.CharField(max_length=64, verbose_name='answer')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'History',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('is_manager', models.BooleanField(default=False, verbose_name='is manager')),
                ('token', models.CharField(max_length=32, verbose_name='token')),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Token',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
